services:
  db:
    image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password
    container_name: warehouse-db
    restart: always
    environment:
      MYSQL_DATABASE: warehouse_go
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3307:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d # Otomatis eksekusi SQL saat startup
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - warehouse-network

  redis:
    image: redis:8-alpine
    container_name: warehouse-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - warehouse-network

  warehouse-api:
    build: .
    container_name: warehouse-api
    restart: always
    ports:
      - "8080:8080"
      - "50053:50053"
    environment:
      REDIS_ADDRESS: warehouse-redis:6379
      ENABLE_LOW_STOCK_ALERT: "true"
      LOW_STOCK_ALERT_EMAIL: "admin@warehouse.com"
      AUDIT_SERVICE_URL: "audit-service:50052"
      JWT_SECRET: "rahasia-super-aman"
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "rootpassword"
      DB_NAME: warehouse_go
      API_PORT: 8080
      GRPC_PORT: 50053
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - warehouse-network

networks:
  warehouse-network:
    external: true