// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/warehouse.proto

package warehouse

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // Minimal 1 item
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdateRequest) Reset() {
	*x = StockUpdateRequest{}
	mi := &file_proto_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdateRequest) ProtoMessage() {}

func (x *StockUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdateRequest.ProtoReflect.Descriptor instead.
func (*StockUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *StockUpdateRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // item_id harus lebih besar dari 0
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`           // quantity harus lebih besar dari 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_proto_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *StockItem) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *StockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type StockUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdateResponse) Reset() {
	*x = StockUpdateResponse{}
	mi := &file_proto_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdateResponse) ProtoMessage() {}

func (x *StockUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdateResponse.ProtoReflect.Descriptor instead.
func (*StockUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *StockUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_warehouse_proto protoreflect.FileDescriptor

const file_proto_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x15proto/warehouse.proto\x12\twarehouse\x1a\x17validate/validate.proto\"J\n" +
	"\x12StockUpdateRequest\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x14.warehouse.StockItemB\b\xfaB\x05\x92\x01\x02\b\x01R\x05items\"R\n" +
	"\tStockItem\x12 \n" +
	"\aitem_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06itemId\x12#\n" +
	"\bquantity\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bquantity\"/\n" +
	"\x13StockUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2b\n" +
	"\x10WarehouseService\x12N\n" +
	"\rIncreaseStock\x12\x1d.warehouse.StockUpdateRequest\x1a\x1e.warehouse.StockUpdateResponseBZ\n" +
	"\x16com.pconk.warehouse.v1B\x0eWarehouseProtoP\x01Z.warehouse-management-api/internal/pb/warehouseb\x06proto3"

var (
	file_proto_warehouse_proto_rawDescOnce sync.Once
	file_proto_warehouse_proto_rawDescData []byte
)

func file_proto_warehouse_proto_rawDescGZIP() []byte {
	file_proto_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_warehouse_proto_rawDesc), len(file_proto_warehouse_proto_rawDesc)))
	})
	return file_proto_warehouse_proto_rawDescData
}

var file_proto_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_warehouse_proto_goTypes = []any{
	(*StockUpdateRequest)(nil),  // 0: warehouse.StockUpdateRequest
	(*StockItem)(nil),           // 1: warehouse.StockItem
	(*StockUpdateResponse)(nil), // 2: warehouse.StockUpdateResponse
}
var file_proto_warehouse_proto_depIdxs = []int32{
	1, // 0: warehouse.StockUpdateRequest.items:type_name -> warehouse.StockItem
	0, // 1: warehouse.WarehouseService.IncreaseStock:input_type -> warehouse.StockUpdateRequest
	2, // 2: warehouse.WarehouseService.IncreaseStock:output_type -> warehouse.StockUpdateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_warehouse_proto_init() }
func file_proto_warehouse_proto_init() {
	if File_proto_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_warehouse_proto_rawDesc), len(file_proto_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_warehouse_proto_msgTypes,
	}.Build()
	File_proto_warehouse_proto = out.File
	file_proto_warehouse_proto_goTypes = nil
	file_proto_warehouse_proto_depIdxs = nil
}
