// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/warehouse.proto

package warehouse

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StockUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StockUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StockUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StockUpdateRequestMultiError, or nil if none found.
func (m *StockUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StockUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetItems()) < 1 {
		err := StockUpdateRequestValidationError{
			field:  "Items",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, StockUpdateRequestValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, StockUpdateRequestValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return StockUpdateRequestValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return StockUpdateRequestMultiError(errors)
	}

	return nil
}

// StockUpdateRequestMultiError is an error wrapping multiple validation errors
// returned by StockUpdateRequest.ValidateAll() if the designated constraints
// aren't met.
type StockUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StockUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StockUpdateRequestMultiError) AllErrors() []error { return m }

// StockUpdateRequestValidationError is the validation error returned by
// StockUpdateRequest.Validate if the designated constraints aren't met.
type StockUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StockUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StockUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StockUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StockUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StockUpdateRequestValidationError) ErrorName() string {
	return "StockUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StockUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStockUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StockUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StockUpdateRequestValidationError{}

// Validate checks the field values on StockItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StockItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StockItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StockItemMultiError, or nil
// if none found.
func (m *StockItem) ValidateAll() error {
	return m.validate(true)
}

func (m *StockItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetItemId() <= 0 {
		err := StockItemValidationError{
			field:  "ItemId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetQuantity() <= 0 {
		err := StockItemValidationError{
			field:  "Quantity",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StockItemMultiError(errors)
	}

	return nil
}

// StockItemMultiError is an error wrapping multiple validation errors returned
// by StockItem.ValidateAll() if the designated constraints aren't met.
type StockItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StockItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StockItemMultiError) AllErrors() []error { return m }

// StockItemValidationError is the validation error returned by
// StockItem.Validate if the designated constraints aren't met.
type StockItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StockItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StockItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StockItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StockItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StockItemValidationError) ErrorName() string { return "StockItemValidationError" }

// Error satisfies the builtin error interface
func (e StockItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStockItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StockItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StockItemValidationError{}

// Validate checks the field values on StockUpdateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StockUpdateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StockUpdateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StockUpdateResponseMultiError, or nil if none found.
func (m *StockUpdateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StockUpdateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return StockUpdateResponseMultiError(errors)
	}

	return nil
}

// StockUpdateResponseMultiError is an error wrapping multiple validation
// errors returned by StockUpdateResponse.ValidateAll() if the designated
// constraints aren't met.
type StockUpdateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StockUpdateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StockUpdateResponseMultiError) AllErrors() []error { return m }

// StockUpdateResponseValidationError is the validation error returned by
// StockUpdateResponse.Validate if the designated constraints aren't met.
type StockUpdateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StockUpdateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StockUpdateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StockUpdateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StockUpdateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StockUpdateResponseValidationError) ErrorName() string {
	return "StockUpdateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StockUpdateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStockUpdateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StockUpdateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StockUpdateResponseValidationError{}
