// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audit/audit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pelaku & Lokasi
	Username    string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	WarehouseId string `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Role        string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// Detail Transaksi
	Action          string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // Contoh: "STOCK_OUT", "ADJUSTMENT"
	Sku             string `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	ProductName     string `protobuf:"bytes,6,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	QuantityChanged int32  `protobuf:"varint,7,opt,name=quantity_changed,json=quantityChanged,proto3" json:"quantity_changed,omitempty"`
	FinalStock      int32  `protobuf:"varint,8,opt,name=final_stock,json=finalStock,proto3" json:"final_stock,omitempty"`
	// Metadata & Waktu
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Digunakan untuk {"request_id": "UUID"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_audit_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuditRequest) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *AuditRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuditRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *AuditRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *AuditRequest) GetQuantityChanged() int32 {
	if x != nil {
		return x.QuantityChanged
	}
	return 0
}

func (x *AuditRequest) GetFinalStock() int32 {
	if x != nil {
		return x.FinalStock
	}
	return 0
}

func (x *AuditRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_audit_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_audit_audit_proto protoreflect.FileDescriptor

const file_audit_audit_proto_rawDesc = "" +
	"\n" +
	"\x11audit/audit.proto\x12\x05audit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x03\n" +
	"\fAuditRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12!\n" +
	"\fproduct_name\x18\x06 \x01(\tR\vproductName\x12)\n" +
	"\x10quantity_changed\x18\a \x01(\x05R\x0fquantityChanged\x12\x1f\n" +
	"\vfinal_stock\x18\b \x01(\x05R\n" +
	"finalStock\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12=\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2!.audit.AuditRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\rAuditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2H\n" +
	"\fAuditService\x128\n" +
	"\vLogActivity\x12\x13.audit.AuditRequest\x1a\x14.audit.AuditResponseB\x18Z\x16async-audit-service/pbb\x06proto3"

var (
	file_audit_audit_proto_rawDescOnce sync.Once
	file_audit_audit_proto_rawDescData []byte
)

func file_audit_audit_proto_rawDescGZIP() []byte {
	file_audit_audit_proto_rawDescOnce.Do(func() {
		file_audit_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_audit_proto_rawDesc), len(file_audit_audit_proto_rawDesc)))
	})
	return file_audit_audit_proto_rawDescData
}

var file_audit_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_audit_audit_proto_goTypes = []any{
	(*AuditRequest)(nil),          // 0: audit.AuditRequest
	(*AuditResponse)(nil),         // 1: audit.AuditResponse
	nil,                           // 2: audit.AuditRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_audit_audit_proto_depIdxs = []int32{
	3, // 0: audit.AuditRequest.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: audit.AuditRequest.metadata:type_name -> audit.AuditRequest.MetadataEntry
	0, // 2: audit.AuditService.LogActivity:input_type -> audit.AuditRequest
	1, // 3: audit.AuditService.LogActivity:output_type -> audit.AuditResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_audit_audit_proto_init() }
func file_audit_audit_proto_init() {
	if File_audit_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_audit_proto_rawDesc), len(file_audit_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_audit_proto_goTypes,
		DependencyIndexes: file_audit_audit_proto_depIdxs,
		MessageInfos:      file_audit_audit_proto_msgTypes,
	}.Build()
	File_audit_audit_proto = out.File
	file_audit_audit_proto_goTypes = nil
	file_audit_audit_proto_depIdxs = nil
}
